import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { DEMOS } from './demo-content.mjs';
import { DEMO_PAGES } from './demo-routes.mjs';
import { translations, unchanged, dynamicCopy } from './translations.mjs';

export const normalize = value => value.replace(/\s+/g, ' ').trim();
const decode = value => value.replace(/&(#x[\da-f]+|#\d+|amp|quot|apos|lt|gt|nbsp);/gi, (match, code) => ({ amp: '&', quot: '"', apos: "'", lt: '<', gt: '>', nbsp: ' ' })[code] ?? (code.startsWith('#x') ? String.fromCodePoint(parseInt(code.slice(2), 16)) : code.startsWith('#') ? String.fromCodePoint(Number(code.slice(1))) : match));

// These pages are our own generated HTML. Scripts/styles/comments are excluded
// before extracting text and the human-readable attributes we translate.
export function pageStrings(html) {
  const values = new Set();
  const add = value => { value = normalize(decode(value)); if (/\p{L}/u.test(value)) values.add(value); };
  const clean = html.replace(/<!--[^]*?-->|<(script|style)\b[^>]*>[^]*?<\/\1>/gi, '');
  for (const part of clean.split(/(<[^>]+>)/g)) {
    if (!part.startsWith('<')) add(part);
    else {
      for (const match of part.matchAll(/(?:alt|title|placeholder|aria-label)="([^"]*)"/g)) add(match[1]);
      if (/^<meta\b/.test(part) && /(?:name="description"|(?:property|name)="(?:og|twitter):(?:title|description|image:alt)")/.test(part)) {
        const content = part.match(/content="([^"]*)"/); if (content) add(content[1]);
      }
      const href = part.match(/href="(https:\/\/wa.me\/[^"]+)"/);
      if (href) { const text = new URL(decode(href[1])).searchParams.get('text'); if (text) add(text); }
    }
  }
  return values;
}

export function makeDictionary() {
  const dictionary = { ...translations };
  const translate = (text, index) => dictionary[text]?.[index] ?? text;
  for (const demo of Object.values(DEMOS)) {
    dictionary[`${demo.label} · Demo`] = [0, 1].map(i => `${translate(demo.label, i)} · Demo`);
    dictionary[`${demo.brand} — ${demo.label.split(' · ')[0]} | Demo TRAZA`] = [0, 1].map(i => `${demo.brand} — ${translate(demo.label, i).split(' · ')[0]} | Demo TRAZA`);
    dictionary[`Demo conceptual de ${demo.brand}. ${demo.description}`] = [0, 1].map(i => `${i ? 'Demo conceitual de' : 'Concept demo for'} ${demo.brand}. ${translate(demo.description, i)}`);
    dictionary[`Ambiente de ${demo.brand}`] = [`Inside ${demo.brand}`, `Ambiente da ${demo.brand}`];
    dictionary[`Hola, vi la demo ${demo.brand} de TRAZA y quiero una web así para mi negocio.`] = [`Hi, I saw TRAZA's ${demo.brand} demo and would like a website like this for my business.`, `Olá, vi a demo ${demo.brand} da TRAZA e quero um site assim para o meu negócio.`];
    for (const title of [...demo.services.map(service => service[1]), ...(demo.catalog || []).map(plant => plant.name)]) {
      dictionary[`Consultar por la demo ${demo.brand}: ${title}`] = [`Ask about the ${demo.brand} demo: ${translate(title, 0)}`, `Consultar sobre a demo ${demo.brand}: ${translate(title, 1)}`];
      dictionary[`Hola, vi la demo ${demo.brand} de TRAZA, en la sección ${title}, y quiero una web así para mi negocio.`] = [`Hi, I saw TRAZA's ${demo.brand} demo, in the ${translate(title, 0)} section, and would like a website like this for my business.`, `Olá, vi a demo ${demo.brand} da TRAZA, na seção ${translate(title, 1)}, e quero um site assim para o meu negócio.`];
    }
  }
  return dictionary;
}

export const isUnchanged = value => unchanged.includes(value) || Object.values(DEMOS).some(d => value === d.brand || value === d.location || value === d.person && !/FAMILIA|DIRECTOR|NOVIOS/.test(value)) || /^[\d.,+%:/–—\s]+(?:min|h|k|max)?$/.test(value);

export async function addTranslations(output) {
  const dictionary = makeDictionary();
  for (const { source } of DEMO_PAGES) {
    const path = join(output, source);
    let html = await readFile(path, 'utf8');
    const strings = pageStrings(html);
    const missing = [...strings].filter(value => !dictionary[value] && !isUnchanged(value));
    if (missing.length) throw new Error(`Missing translations in ${source}:\n${missing.join('\n')}`);
    // Only ship the copy used by this page, plus labels generated by interactions.
    const copy = Object.fromEntries(Object.entries(dictionary).filter(([key]) => strings.has(key) || dynamicCopy.includes(key)));
    const prefix = source.startsWith('/1_basico/pages/') ? '../../' : '../';
    const data = JSON.stringify(copy).replaceAll('<', '\\u003c');
    html = html.replace('</head>', `<link rel="stylesheet" href="${prefix}assets/languages.css?v=20260924-dropdown">\n<script id="demo-translations" type="application/json">${data}</script>\n<script src="${prefix}assets/languages.js?v=20260924-dropdown" defer></script>\n</head>`);
    // Put i18n before motion and page scripts so every dynamic label can use it.
    const motion = html.match(/<script[^>]+src="[^"]*assets\/motion.js[^"]*"[^>]*><\/script>/)?.[0];
    if (motion) html = html.replace(motion, '').replace('</head>', `${motion}\n</head>`);
    await writeFile(path, html);
  }
}
